inherit_gem:
  bixby: bixby_default.yml

Lint/HandleExceptions:
  Exclude:
    - lib/tufts/curation/indexer.rb
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tufts/curation/spec/**/*'
    - 'lib/tufts/curation/schema/**/*'
Metrics/MethodLength:
  Exclude:
    - lib/tufts/curation/indexer.rb
Naming/FileName:
  Exclude:
    - '**/Gemfile'
    - '*.gemspec'
