name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    continue-on-error: ${{ matrix.experimental }}
    runs-on: ubuntu-latest

    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      DEFAULT_ADMIN_SET: 'default'
      DATABASE_AUTH: true
      DATA_STORAGE: ./public
      TEMP_STORAGE: ./public
      ALLOW_NOTIFICATIONS: true
      DB_DATABASE: epigaea_test
      DB_USER: root
      DB_PASSWORD: root
      TRAVIS: true

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379      
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7']
        experimental: [false]
        include:
          - ruby-version: 3.0
            experimental: true

    steps:
    - name: Install OS packages
      run: |
        sudo apt-get update
        sudo apt-get install unzip imagemagick ghostscript libpq-dev libxslt-dev
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: "2.1.4"
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Update rubygems
      run: |
        gem update --system 3.3.27
        gem install bundler:2.1.4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup hyrax test environment
      run: |
        bundle exec rake hydra:test_server &
        sleep 150        
    - name: Compile assets
      run: |
        bundle exec rails assets:precompile &> /dev/null
    - name: Run tests
      run: xvfb-run -a bundle exec rake ci
      env:
        RAILS_ENV: test        
        TMPDIR: /tmp
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
